### ISSUE TITLE
python-mido version and Debian (Stretch) stable

### ISSUE THREAD

**Issue by trebmuh** [dagargo/microdude#4]
I can see [in the code](https://github.com/dagargo/microdude/blob/master/setup.py#L15) that the mido version needed is _1.2.1_. The [current Debian Stretch version is 1.1.8](https://packages.debian.org/stretch/python-mido). Do you think it could be possible to make microdude able to build with the 1.1.8 version provided by Debian Stretch?

**Comment by erwan35** [comment]
Hello,

I have just tested with the mido version included in stretch (1.1.8) and i'm getting this:

`ERROR:microdude.connector:IOError while connecting: "Connection error"`

So I presume that microdudes really needs at least the 1.2.1.

Cheers
Erwan

**Comment by dagargo** [comment]
After thinking about the current situation, I decided to support Debian Stretch instead of Buster, so I updated the code to work with the current distribution packages instead of using pip3 to install packages.
To accomplish this, I had to change the mido backend from rtmidi to PortMidi because python3-rtmidi is not included in Stretch.

The problem is that the mido version currently available in Buster (1.2.8) is not working with PortMidi. See mido/mido#169. Besides the recommended backend is rtmidi.

Thus, the plan is to move to rtmidi when it goes into Debian stable. While mido version in Buster is 1.2.8, we would have to use the newly created buster branch.

What do you think about this? Is it working for you?

**Comment by trebmuh** [comment]
That's awesome! :+1: 

I've made a package for microdude, for my LibraZiK-2 project. LZK-2 is a debian-based (stretch) linux audio distro. The package will be in test for a few more days before hitting the users' repo, but @erwan35 already tested it a bit and told me that so far so good.

Thanks @dagargo

**Comment by dagargo** [comment]
As it seems to be working, I have increased the version and created the 1.3.1 tag. It would be better if you could package this.
Thanks!

**Comment by trebmuh** [comment]
hi @dagargo 
I've been packaging the 1.3.1 version. I hope @erwan35 will be able to test it soon and confirm that everything is going fine.
Thanks for the move.

**Comment by dagargo** [comment]
Hi!

I've just realized the tag 1.3.1 is pointing to the wrong commit. Even worse, is not pointing to the master branch.

So, if you created the package from the master branch this should not be a problem; but if you created it from the tag it would be using the code for Debian Buster and should not work with Stretch.
So, could you please check this out?
If it's not a problem for you, I'll fix the tag once this is clear.

I'm really sorry for the inconvenience.
And thanks for taking the time to contribute to this project!

**Comment by trebmuh** [comment]
Hi @dagargo : I've build it using https://github.com/dagargo/microdude/archive/1.3.1.tar.gz and @erwan35 tested and reported it working.
If you want to change the tarball, I'd recommend to tag it 1.3.2 in order to avoid bad situation (the tagged releases need to be reproducible in order to ensure security).

**Comment by dagargo** [comment]
If 1.3.1 (tarball) works in Stretch it is because the python-rtmidi is installed from outside the repository.

So, to fix 1.3.1 I have

- merged the buster branch in master, so I don't break any references;
- modified the code to use libportmidi backend again;
- released 1.3.2; and
- deleted the buster branch because it is no longer needed as libportmidi is working again in Buster.

Again, sorry for the inconveniences.

Thanks for supporting the project.

**Comment by trebmuh** [comment]
Hi @dagargo 
I've been packaging the 1.3.2 which is now in its test phase. I hope @erwan35 will be able to test it soon and report back that everything is working as expected.

**Comment by erwan35** [comment]
Hello world,

Thanks ! It's working fine for me.

Cheers
Erwan

**Comment by dagargo** [comment]
Nice!

Thanks for taking the time to test it!

**Comment by trebmuh** [comment]
@dagargo just to let you know that as of today, 1.3.2 is available for all the LibraZiK-2 users. Thanks for this nice piece of software!

... and thanks to @erwan35 to have tested it :wink:
